import { useSession } from 'next-auth/react';
import Head from 'next/head';
import React from 'react'
import { useRecoilState } from 'recoil';
import { modalState } from '../atoms/modalAtom';
import Login from './Login';
import Modal from './Modal';
import Sidebar from './Sidebar';

function Layout({children, providers}) {
    const { data: session } = useSession();
    const [isOpen, setIsOpen] = useRecoilState(modalState);
  
    if (!session) return <Login providers={providers} />;
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className="bgColor min-h-screen flex max-w-[1500px] mx-auto">
          <Sidebar />
         

          {children}
          {isOpen && <Modal />}

        </main>
      </div>
    );
}

export default Layout